language: node_js
node_js: lts/*

install:
 - yarn install --frozen-lockfile

script:
 - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: blog/.vuepress/dist
  repo: jspecter/jspecter.github.io
  target_branch: master
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
